import tsp_draw.dithering
import tsp_draw.process_vertices
import tsp_draw.base
import tsp_draw.size_scale
import tsp_draw.neighbors
import tsp_draw.size_neighbors
import tsp_draw.graphics
import tsp_draw.jobs
import tsp_draw.interactive
